---

# get all hosts for all proxies
- name: get old proxy
  local_action:
    module: zabbix_api
    server_url: "http://{{ inventory_hostname }}:9595/"
    login_user: "{{ zabbix_apiuser }}"
    login_password: "{{ zabbix_apipw }}"
    api_object: "proxy"
    api_method: "get"
    api_options:
        {"filter": {"host": "{{ old_proxy.host }}"}}
  register: old_proxy_obj
- name: get new proxy
  local_action:
    module: zabbix_api
    server_url: "http://{{ inventory_hostname }}:9595/"
    login_user: "{{ zabbix_apiuser }}"
    login_password: "{{ zabbix_apipw }}"
    api_object: "proxy"
    api_method: "get"
    api_options:
        {"filter": {"host": "{{ new_proxy.host }}"}}
  register: new_proxy_obj

- name: get hosts monitored by old proxy
  local_action:
    module: zabbix_api
    server_url: "http://{{ inventory_hostname }}:9595/"
    login_user: "{{ zabbix_apiuser }}"
    login_password: "{{ zabbix_apipw }}"
    api_object: "host"
    api_method: "get"
    api_options:
        {"filter": {"proxy_hostid": "{{ old_proxy_obj.result[0].proxyid }}"}}
  register: mon_hosts

- name: move hosts to another proxy
  local_action:
    module: zabbix_api
    server_url: "http://{{ inventory_hostname }}:9595/"
    login_user: "{{ zabbix_apiuser }}"
    login_password: "{{ zabbix_apipw }}"
    api_object: "host"
    api_method: "update"
    api_options:
        {"hostid": "{{ item.hostid }}",
         "proxy_hostid": "{{ new_proxy_obj.result[0].proxyid }}"} 
  loop: "{{ mon_hosts.result }}"
