---
# This role gets all proxies from the zabbix server including their interface information
- name: Get proxies from Zabbix Server
  local_action:
    module: zabbix_api
    server_url: "http://{{ inventory_hostname }}:9595/"
    login_user: "{{ zabbix_apiuser }}"
    login_password: "{{ zabbix_apipw }}"
    api_object: "proxy"
    api_method: "get"
    api_options:
      {"selectInterface": "extend",
      "selectHosts": "extend"}
  register: zabbix_proxies

- name: Set proxies fact
  set_fact:
    zabbix_proxies: "{{ zabbix_proxies.result }}"

#- name: Save downloaded proxies in "proxies.json"
#  local_action:
#    module: copy
#    content: "{{ zabbix_proxies }}"
#    dest: "{{ playbook_dir }}/proxies.json"

- name: Output configured proxies
  debug:
    msg: "Proxy {{ item.host }} is {{ item.interface.dns }} / {{ item.interface.ip }} (Using IP: {{ item.interface.useip }})"
  loop: "{{ zabbix_proxies }}"

- name: Ping proxy
  delegate_to: item.interface.dns
  debug:
    msg: "I am monitoring {{ item.hosts }}"
  loop: "{{ zabbix_proxies }}"
